### ISSUE TITLE
Initial Startup issue

### ISSUE THREAD

**Issue by Kranzy** [cbrandlehner/homebridge-docker#2]
Hi, I cant seem to load multiple scripts in the package.json file. I have used your demo as a starting point and it always fails stating an accessory was not registered with a plugin. The log seems to show only the last npm install script in the list is being run.

Currently the contents of the file is:

`
{
    "scripts": {
        "install": "npm install -g homebridge-efergy",
        "install": "npm install -g homebridge-onkyo-avr"
    }
}
`
Only the oknyo-avr plugin gets installed.
Any ideas?

Let me know if you require more information.

**Comment by partymike** [comment]
I had the same problem, solved it by:

{ 	"scripts": {
	"install": "npm install -g homebridge-synology homebridge-sonos --unsafe-perm",
	"install": "npm install -g homebridge-sonos --unsafe-perm",
	"install": "npm install -g homebridge-lightwaverf --unsafe-perm",
	"install": "npm install -g homebridge-synology --unsafe-perm",
	"install": "npm install -g homebridge-wakeonlan@1.0.0 --unsafe-perm",
	"install": "npm install -g homebridge-samsungtv-control@1.1.0 --unsafe-perm",
	"install": "npm install -g homebridge-harmonyhub@0.2.0-alpha --unsafe-perm",
	"install": "npm install -g homebridge-nest --unsafe-perm"
	}
}

Not sure why you have to dupe say sonos twice thought for it to run....

Also, I got lots of package errors say when trying to install homebridge-wakeonlan so I installed manually and saw that it added the @1.0.0 to the end. I replicated this in the package file and then it worked like a charm.

Hope this helps.
MIke

**Comment by Kranzy** [comment]
I used the same script you just posted and the only plugin that gets installed is the last in the list which is nest. 

I think its to do with the same key being used in a json file. I was able to work around it by using && between commands inside a single install however I would like to have it separated if possible for readability.

**Comment by partymike** [comment]
Strangely enough since i posted the above it no longer works...

Any chance you could post your example, have tried a LOT of variations and none seem to work....

Cheers

**Comment by Kranzy** [comment]
This is what I am currently using to load a few test packages.

`{ "scripts": {
		"install": " npm install -g homebridge-http && npm install -g homebridge-onkyo-avr && npm install -g homebridge-ssh-garagedoor"
	}
}`

**Comment by snikch** [comment]
The configuration is a json object, and you were sending through multiple values with the same key. Keys should be unique, so each time "install" was used as a key, it overwrote the previous one.

**Comment by cbrandlehner** [comment]
closing, problem seems to be fixed by using the configuration @Kranzy shared in his comment.
