### ISSUE TITLE
Initiat start

### ISSUE THREAD

**Issue by luckymentrix** [cbrandlehner/homebridge-docker#3]
Hi! Currently i've got a strange issue: cant get homebrigde to work cause cant get the container to run.

I've installed docker, use the image cbrandlehner/homebridge0.14, create a container with the map /root/.homebridge.

In the map /volume1/docker/homebridge i've added 3 files, see attachments below.

I start the container in docker and watch through terminal what happens. I get some strange issues. Hope you can help me. 

Terminal messages: 
http://mennovandenberg.nl/tmp/homebridge.html

NPM debug:
http://mennovandenberg.nl/tmp/npm-debug.log

When i try to start from ssh and run "docker run -d --net=host --name=homebridge -p 51826:51826 -v /volume1/docker/homebridge:/root/.homebridge cbrandlehner/homebridge:0.14" i get the message 
"docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'."

Hope you can help me!

![config](https://cloud.githubusercontent.com/assets/20353745/16683048/18ecd996-44fe-11e6-83cb-fcc03be930f7.JPG)
![homebridge](https://cloud.githubusercontent.com/assets/20353745/16683047/18e962c0-44fe-11e6-9630-86d3e4e80bf0.JPG)
![package](https://cloud.githubusercontent.com/assets/20353745/16683049/18ed32c4-44fe-11e6-8ac6-e5f62e81e053.JPG)

**Comment by cbrandlehner** [comment]
have you started the docker package on your synology? Were you able to run other docker images?

**Comment by luckymentrix** [comment]
Yes i started the docker package on my synology, I did test with other homebridge images: also not working

**Comment by cbrandlehner** [comment]
Please contact Synology support - this seems to be a general problem with docker and not a specific problem with this image.
